### ISSUE TITLE
erro na interpretação do comando 

### ISSUE THREAD

**Issue by calebe42** [igorquintaes/Discans#6]
o bot afirma Link "inválido T_T'" para links do site "Union Mangás" mesmo  o link dado como exemplo

**Comment by igorquintaes** [comment]
Pode ser três coisas:

A primeira é que o site da Union Mangás só é acessível dentro de solo brasileiro, então um servidor hospedado fora do Brasil não teria acesso ao site e retornaria esse erro.

A segunda é que o site da Union, nos últimos anos, se tornou bem ruim e muitas vezes não carrega.

A terceira é a necessidade de atualização dos XPATHs para reconhecimento da página e das informações contidas nela, [neste arquivo](https://github.com/igorquintaes/Discans/blob/master/Discans.Shared/DiscordServices/CrawlerSites/UnionMangasCrawlerService.cs) e também [neste arquivo](https://github.com/igorquintaes/Discans/blob/master/Discans.Shared/DiscordServices/CrawlerService.cs). Por razões pessoais não tive disposição de editar o projeto da Discans recentemente. Se quiser, pode ver esse ponto e abrir um PR, senão virei a investigar e corrigir futuramente
